### ISSUE TITLE
Integration tests and CI are needed

### ISSUE THREAD

**Issue by vangorra** [prime-8-consulting/meteor-oauth2#12]
Integration tests for the login process should be written. Meteor 1.3, phantomjs and travis would be a good fit.

**Comment by awatson1978** [comment]
Yeah, so, as part of the HL7 FHIR project, my clients are definitely going to want to integration tests on the OAuth components.  We have a [Quality Assurance Initiative](http://clinical.meteor.com/quality-control) in place, and you can check out the [Continuous Integration Dashboard](https://circleci.com/build-insights) across the entire `clinical` track.  We tried using Travis CI for quite awhile, and eventually migrated to CircleCI and have been having much better success with it.  

At some point, our particular industry stakeholders are going to want to integrate our signInPage at step A3 I think it is.  Our signIn page is in the [ `clinical:active-entry`](https://github.com/clinical-meteor/active-entry) package, and we have [screenshots](https://github.com/clinical-meteor/active-entry/tree/master/docs) available for design review and iteration.  That's going to be an opinionated decision to do that integration, however, and folks using `useraccounts:core` or have strong widget library preferences aren't going to want our particular sign-in page embedded in this library.  So we'll need to shuffle the packages around a bit to figure out how to manage those differing interests.

The upside of a `clinical:active-entry` integration, however, is that we already have [a bunch of integration tests written](https://github.com/clinical-meteor/active-entry/blob/master/tests/gagarin/activeEntryTests.js); and you can [see their build history](https://circleci.com/gh/clinical-meteor/active-entry), and check out the [.circle.yml configuration file](https://github.com/clinical-meteor/active-entry/blob/master/circle.yml).  We also have a growing collection of [Gagarin integration test examples](https://github.com/clinical-meteor/cookbook/blob/master/cookbook/testing.examples.md).

By and large, the [StarryNight](http://starrynight.meteor.com/) infrastructure uses the same Chromedriver for both Nightwatch and Gagarin.  There's strong support in Starrynight/Nightwatch for [using the PhantomJS driver](https://github.com/clinical-meteor/checklist-manifesto/blob/master/webapp/.meteor/nightwatch.json#L57-L71).  All a person has to do is run:

``` bash
starrynight autoconfig
starrynight run-tests --type validation --env phantomjs
```

Nightwatch is generally used for acceptance testing, however.  And while it could definitely navigate testing URLs from multiple servers and ping-pong testing; it's inspection of javascript objects will probably be limited to client-side objects.

[Gagarin support for PhantomJS](https://github.com/anticoders/gagarin#testing-with-browser) is still experimental; but it would allow us to inspect and test server-side javascript objects.  But the jury is still out whether it will be able to test two apps at the same time.

Lastly, I was super excited to see that the packages rely on [Meteor 1.0](https://github.com/prime-8-consulting/meteor-oauth2/blob/master/packages/meteor-oauth2-server/package.js#L9).  That's really good for us, as most of the Clinical track has gravitated towards `METEOR@1.1.0.3`.  We may actually go so far as to downgrading the example apps to `1.1.0.3` for testing purposes; since that's where the rest of the release track is.  The plan is to skip `1.2` altogether, and move to `1.3` later this spring/summer.  

Anyhow, just some thoughts.

**Comment by vangorra** [comment]
Ok. I'm starting to see the scope of what you are working on. It's pretty massive. I think there is a way to balance both the requirements of the clinical project as well as still provide a generic oauth2 solution to the community at large.

Testing:
While we should provide and maintain integration tests for the existing examples. We should also create examples and integration tests specific to clinical meteor. This way we get the best of both worlds. The clinical side gets verification that the the oauth2 process works with the clinical packages and is tested with starrynight, etc. This also gives the rest of the devs who use the oauth2 packages simple examples that depend on core meteor packages.

Downgrading:
We can probably easily downgrade the examples, maybe to 1.0. They aren't doing any spectacular.

**Comment by awatson1978** [comment]
Yup.  We have reason to believe that the healthcare industry is going to make major investments in full-stack Javascript; and it's worth building this stuff out.

We also understand that we have specific needs above-and-beyond the general community needs.  On the other hand, we generally have funding available and can contribute time and resources.  

So, we just need to figure out where the boundaries are, and who's responsible for what.  But for what it's worth, I have three or four established business that are interested in providing public APIs to their data; and OAuth is the path to that.
