### ISSUE TITLE
Initial Refactorings

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#15]
Don't worry; I'm not going to go refactor crazy.  But, there are a few items that could stand to be renamed.  What caught my eye to start with:
- [ ] MeteorOAuth2Server -> MyOAuthService
- [ ] oAuth2Server -> AuthServer

May add a few more suggested refactorings as I study the code a bit more; but those are the two I'd start with.

**Comment by vangorra** [comment]
## MeteorOAuth2Server -> MyOAuthService

Are you referring to the name of the service configuration? While changing it is easy, doing so would require an upgrade path for existing users. Additionally, it is named to closely match the name of the package in order to keep the service configuration namespace sane.

## oAuth2Server -> AuthServer

This change makes sense as the name of the class directly applies to a defined role in the oauth2 protocol. My only concern with refactoring is AuthServer is pretty generic and we should discuss the possibility of conflicts. Whatever is decided should be careful not to pollute the meteor namespace as meteor < 1.3 just includes everything.

**Comment by awatson1978** [comment]
Ah, existing users.  Yeah, we should be able to alias the service, to maintain backwards compatibility.  

And, yes...  talking about the service configuration.  I get _why_ it's named the way it is...  but coming to the code base for the first time.... `MeteorOAuth2Server` and `oAuth2Server` are the two terms that had me scrunching up my eyes and thinking "wait, what is this doing again?".  The Meteor is redundant within the scope of the package; and the service configuration seems like it should be an abstract noun like Service, rather than a concrete noun like Server.

I agree that AuthServer is somewhat generic; although no worse than Template or AccountServer or the other objects from Meteor that get added to the global namespace.  I dunno.  I'm not overly worried by name collisions, I suppose; and am happy to cross those bridges when I get to them.  But that's personal preference.

**Comment by vangorra** [comment]
> MeteorOAuth2Server -> MyOAuthService

Looking through the oauth services in the meteor core packages. The naming convention is named after the service. So "google", "github", "facebook", "meteor" (for the meteor.com site), etc. Since the domain is not known, we should choose something that is highly unlikely to conflict. I tend to think the current name is appropriate as there isn't much advantage to changing it.

> oAuth2Server -> AuthServer

This global variable is provided in the oauth2 server package. The variable name itself it self-descriptive and strongly suggests the package from which it originates. While I am open to a change, "AuthServer" is too generic and does not properly describe what sort of auth it's performing nor provides hints on which package it came from.

I'd say these should stay untouched for now.

**Comment by awatson1978** [comment]
Okay.  I made a healthcare specific fork, and will do these types of refactors there.  Closing.
